"use client";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";

import Link from "next/link";
import {Plus,ArrowUpRight,Files,CheckCircle2,Clock3,ScanLine} from "lucide-react";
import {Panel,Notice,StatusBadge,StatCard,PageHeading,LoadingState,EmptyState,Progress} from "./ui";
import {useApi} from "./hooks";
import {TIERS} from "@/lib/lumindaly/config";
export function Dashboard(){
 const s=useApi("/api/cases");if(s.loading&&!s.data)return <LoadingState/>;if(s.error)return <div className="page-container"><Notice kind="error">{s.error}</Notice></div>;
 const cases=s.data?.cases??[],scans=s.data?.scans??[];
 return <div className="page-container"><PageHeading eyebrow="YOUR WORKSPACE" title="Your next steps, in one place." description="Pick up where you left off. Every case has its own facts, evidence, and progress."><Link href="/scan" className="button secondary small"><Plus size={16}/>New free scan</Link></PageHeading><div className="stats-grid"><StatCard label="Total cases" value={cases.length} icon={Files}/><StatCard label="In progress" value={cases.filter((c:any)=>!["approved","rejected","closed","payment_required"].includes(c.status)).length} icon={Clock3}/><StatCard label="Ready to submit" value={cases.filter((c:any)=>c.status==="ready").length} icon={CheckCircle2}/><StatCard label="Saved scans" value={scans.length} icon={ScanLine}/></div><Panel><div className="inline-actions justify-between"><h2 className="small-heading">My cases</h2><span className="metadata text-muted">{cases.length} case{cases.length===1?"":"s"}</span></div>{cases.length?<div className="table-wrap mt-4"><Table className="case-table"><TableHeader><TableRow><TableHead>Account & case</TableHead><TableHead>Status</TableHead><TableHead>Readiness</TableHead><TableHead>Opened</TableHead><TableHead>Next step</TableHead></TableRow></TableHeader><TableBody>{cases.map((c:any)=><TableRow key={c.id}><TableCell><strong>@{c.username||"Username needed"}</strong><p>{TIERS.find(t=>t.id===c.product_tier)?.name??c.product_tier}</p></TableCell><TableCell><StatusBadge status={c.status}/></TableCell><TableCell><div className="min-w-24"><span className="text-xs">{c.readiness_score}/100</span><Progress value={c.readiness_score} className="mt-2 h-1.5" aria-label="Case readiness"/></div></TableCell><TableCell className="whitespace-nowrap text-muted">{new Date(c.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</TableCell><TableCell><Link href={"/case/"+c.id+(c.status==="ready"?"/appeal":"")} className="inline-flex items-center gap-2 text-sm font-medium text-blue-700">{c.payment_status==="unpaid"?"Continue":c.status==="ready"?"View appeal":"Open case"}<ArrowUpRight size={16}/></Link></TableCell></TableRow>)}</TableBody></Table></div>:<EmptyState title="Your first case starts with a scan." description="Upload the notice from TikTok. We’ll help you organize the context and identify what is missing."><Link href="/scan" className="button primary">Scan My Case — Free <ArrowUpRight size={16}/></Link></EmptyState>}</Panel>{scans.length>0&&<Panel><h2 className="small-heading mb-4">Recent scans</h2><div className="divide-y divide-slate-100">{scans.map((scan:any)=><Link href={"/scan/result/"+scan.id} key={scan.id} className="flex items-center justify-between gap-4 py-4"><div><strong className="text-sm font-medium">{scan.account_type} · {(scan.violation_category??"Manual review required").replace(/_/g," ")}</strong><p className="text-xs mt-1">{new Date(scan.created_at).toLocaleDateString("en-US")}</p></div><ArrowUpRight size={18} className="text-blue-600"/></Link>)}</div></Panel>}</div>;
}
