import { TIERS, money } from "@/lib/lumindaly/config";
import Link from "next/link";
import { ArrowUpRight, ScanLine, FileCheck2, ShieldCheck, Check, ArrowRight } from "lucide-react";
const steps = [
 {n:"01",title:"Scan your notice",text:"Upload a screenshot or paste the exact text. See what is known, what is missing, and what needs review.",icon:ScanLine},
 {n:"02",title:"Build your case",text:"Choose a case package, answer the relevant questions, and add your own supporting documents.",icon:ShieldCheck},
 {n:"03",title:"Review your appeal",text:"Get an organized statement and evidence checklist. You review it and submit through TikTok.",icon:FileCheck2}
];
export default function Home() {
 return <><header className="site-header"><Link href="/" className="brand"><span className="brand-mark"><ScanLine size={20}/></span>Lumindaly<span className="brand-period">.</span></Link><nav className="header-links"><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><Link href="/partner">For partners</Link></nav><div className="header-actions"><Link href="/dashboard" className="login-link">My cases</Link><Link href="/scan" className="button primary small">Free scan <ArrowUpRight size={16}/></Link></div></header><main>
 <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="mini-line"/> A clearer next step for TikTok creators</div><h1>TikTok took action<br/>against your account?<br/><span>Don’t appeal blindly.</span></h1><p className="hero-description">Upload your notice and understand what TikTok is asking for before you submit your appeal.</p><Link href="/scan" className="button primary large">Scan My Case — Free <ArrowRight size={19}/></Link><p className="microcopy"><Check size={15}/> No card required <span>·</span> Your documents stay private</p></div><div className="hero-workspace"><div className="workspace-top"><span><ScanLine size={17}/> YOUR NEXT STEP, ORGANIZED</span><span className="example-tag">Process preview</span></div><div className="workspace-main"><div className="case-icon"><FileCheck2 size={28}/></div><h2>Make your case.<br/>With the right context.</h2><p>A structured workspace for the notice, the facts, and your supporting evidence.</p><div className="preview-steps">{[["01","Understand the notice","Identify what needs to be checked."],["02","Gather the evidence","Build your case from your real documents."],["03","Prepare your appeal","Review your statement before submitting."]].map(([n,t,d])=><div className="preview-step" key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div><Check size={16}/></div>)}</div></div><div className="workspace-foot"><ShieldCheck size={16}/> Private by design. Grounded in your facts.</div></div></section>
 <section className="audience-strip"><div className="container"><span>Built for the moment<br/><strong>your next move matters.</strong></span><span>Creators</span><span>TikTok Shop sellers</span><span>Shop affiliates</span><span>Personal accounts</span></div></section>
 <section id="how-it-works" className="section container"><div className="section-heading"><div><span className="eyebrow">FROM NOTICE TO NEXT STEP</span><h2>A clear path through<br/>a stressful situation.</h2></div><p>Bring the notice. Keep the facts.<br/>Build a dossier you can actually review.</p></div><div className="three-grid">{steps.map(s=><article className="step-card" key={s.n}><div className="step-top"><span>{s.n}</span><s.icon size={24}/></div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
 <section className="checks-section"><div className="container split-section"><div><span className="eyebrow">CLARITY BEFORE ACTION</span><h2>The facts first.<br/>The appeal second.</h2><p>Your case readiness measures how complete your dossier is. It is never a prediction of whether TikTok will approve your appeal.</p><Link href="/scan" className="text-link">See what your notice is missing <ArrowRight size={17}/></Link></div><div className="checks-list">{[["Notice & account context","The exact action, account type, market, and details provided in your notice."],["Rule compatibility","A match to a verified rule, or a manual review state when no match is available."],["Evidence & consistency","Relevant documents, missing details, and facts that need clarification."],["Appeal preparation","A statement based on your real facts, with unresolved issues made visible."]].map(([t,d])=><div key={t}><Check size={19}/><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>
 <section id="pricing" className="section container"><div className="section-heading"><div><span className="eyebrow">ONE CASE. ONE PAYMENT.</span><h2>Start free.<br/>Build when you’re ready.</h2></div><p>No subscription. Your scan helps identify<br/>the package relevant to your situation.</p></div><div className="pricing-grid">{TIERS.filter(t=>["personal","creator","shop_violation"].includes(t.id)).map(({name:t,amount:p,description:d},i)=><article className={"price-card "+(i===1?"featured":"")} key={t}><div className="price-label">{i===1?"FOR CREATORS":"CASE PREPARATION"}</div><h3>{t}</h3><p>{d}</p><div className="price">{money(p).replace(".00","")}<span> / case</span></div><ul><li><Check size={16}/> Structured case builder</li><li><Check size={16}/> Private evidence workspace</li><li><Check size={16}/> Appeal preparation & outcome tracking</li></ul><Link href="/scan" className={"button "+(i===1?"primary":"secondary")}>Start with a free scan <ArrowUpRight size={16}/></Link></article>)}</div><p className="pricing-note">Also available: {TIERS.filter(t=>!["personal","creator","shop_violation"].includes(t.id)).map(t=>t.name+" "+money(t.amount).replace(".00","")).join(" · ")}. Payment covers preparation and review, not a guaranteed outcome.</p></section>
 <section className="partner-banner container"><div><span className="eyebrow">LUMINDALY PARTNERS</span><h2>Help your community<br/>find their next step.</h2><p>Earn 70% on eligible purchases during your first 30 days.<br/>Then 40% on future eligible purchases from attributed customers.</p></div><Link href="/partner" className="button light">Explore the partner program <ArrowUpRight size={18}/></Link></section>
 <section className="section container faq-section"><div><span className="eyebrow">GOOD QUESTIONS</span><h2>Before you<br/>take the next step.</h2></div><div className="faq-list">{[["Does Lumindaly guarantee my account will be restored?","No. TikTok makes the final decision. Lumindaly helps you understand your notice and prepare a dossier using your actual facts and documents."],["What if my notice doesn’t match a verified rule?","Your scan is marked Manual review required. Unknown deadlines, appeal limits, and policy details remain unknown until they can be verified."],["Do I need to pay to scan my notice?","No. Run a free scan before choosing a paid case package. No card is required for the scan."],["Does Lumindaly submit the appeal for me?","No. You review your appeal package and submit it through the appropriate TikTok channel. Never share your TikTok password."],["Can I open more than one case?","Yes. Each purchase covers a separate case. Your dashboard organizes cases across multiple TikTok accounts."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 </main><footer className="site-footer container"><Link href="/" className="brand">Lumindaly<span className="brand-period">.</span></Link><p>Lumindaly is independent and is not affiliated with TikTok or ByteDance.</p><Link href="/scan">Scan your case <ArrowUpRight size={14}/></Link></footer></>;
}
